# spring:
#   application:
#     name: restaurant

#   cloud:
#     config:
#       uri: http://localhost:8891

# server:
#   port: 8080

server:
  port: 8080
  servlet-path: /*
  contextPath: /restaurant